<?php
$z[0]=Array("title","",542,556);
$z[0][4]=array();
$z[1]=Array("litpic","",572,587);
$z[1][4]=array();
$z[2]=Array("pubdate","",1021,1063);
$z[2][4]=array();
$z[2][4]['function']="GetDateMK(@me)";
$z[3]=Array("arcurl","",1128,1143);
$z[3][4]=array();
$z[4]=Array("title","",1293,1307);
$z[4][4]=array();
$z[5]=Array("description","",1456,1523);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(html2text(@me),150).\"...\"";

?>