<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img  src='{@me['litpic']}'/></a>\"); ",401,590);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",755,770);
$z[1][4]=array();
$z[2]=Array("pubdate","",855,901);
$z[2][4]=array();
$z[2][4]['function']="GetDateTimeMK(@me)";
$z[3]=Array("arcurl","",967,982);
$z[3][4]=array();
$z[4]=Array("title","",1105,1119);
$z[4][4]=array();
$z[5]=Array("description","",1218,1281);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\"),200)";

?>