<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img  src='{@me['litpic']}'/></a>\"); ",581,770);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",785,800);
$z[1][4]=array();
$z[2]=Array("title","",816,830);
$z[2][4]=array();
$z[3]=Array("pubdate","",855,901);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("description","",926,946);
$z[4][4]=array();
$z[5]=Array("pubdate","",1576,1622);
$z[5][4]=array();
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("arcurl","",1655,1670);
$z[6][4]=array();
$z[7]=Array("title","",1858,1872);
$z[7][4]=array();
$z[8]=Array("description","",1964,1984);
$z[8][4]=array();

?>