<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img src='{@me['litpic']}'/></a>\"); ",581,769);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",2019,2036);
$z[1][4]=array();
$z[2]=Array("arcurl","",2051,2066);
$z[2][4]=array();
$z[3]=Array("title","",2082,2096);
$z[3][4]=array();
$z[4]=Array("pubdate","",2145,2191);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2216,2230);
$z[5][4]=array();
$z[6]=Array("scores","",2255,2270);
$z[6][4]=array();
$z[7]=Array("description","",2303,2323);
$z[7][4]=array();

?>