<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",6,160);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",171,186);
$z[1][4]=array();
$z[2]=Array("title","",202,216);
$z[2][4]=array();
$z[3]=Array("pubdate","",267,313);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",339,353);
$z[4][4]=array();
$z[5]=Array("scores","",379,394);
$z[5][4]=array();
$z[6]=Array("description","",424,444);
$z[6][4]=array();

?>