<?php
$z[0]=Array("field","",208,238);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",264,293);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","<li class=\"xiala\" style=\"background-color:#f13a3a ; border-radius: 4px;\"><a class=\"\" style=\"color: #fff;\" href=\"[field:typelink/]\">[field:typename/]</a></li>",326,523);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[3]=Array("field","",529,581);
$z[3][4]=array();
$z[3][4]['name']="typeid";
$z[3][4]['function']="gettoptype(@me,link)";

?>