<div class='itemCenter toubuhover' style="float: left; height: 40px;width: 95px; margin-left: 10px;">
																	<li>
																		<a hidefocus='true' style='outline:none; ' class='topwen' href='{dede:field name=' typeurl '/}' onclick="return false;">{dede:field name='typename'/}<span class='itemName0'>
	


{dede:channel type='son'}<li class="xiala" style="background-color:#f13a3a ; border-radius: 4px;"><a class="" style="color: #fff;" href="[field:typelink/]">[field:typename/]</a></li>{/dede:channel}


{dede:field.typeid function="gettoptype(@me,link)"/}
</span></a>
																	</li>
																</div>