<div class='itemCenter toubuhover' style="float: left; height: 100px; width: 95px; margin-left: 5px;overflow: visible;"><li><a hidefocus='true' style='outline:none; color: black ;' class='' href='{dede:field name='typeurl'/}'  onclick="return false;">{dede:field name='typename'/}<span class='itemName0'>
	

<ul>
{dede:channel type='son'}<li><a href="[field:typelink/]">[field:typename/]</a></li>{/dede:channel}
</ul>


</span></a></li></div>