<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img  src='{@me['litpic']}' class=\"J_newsListPic newsPic newsListNewPic\"/></a>\"); ",581,815);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",2065,2082);
$z[1][4]=array();
$z[2]=Array("arcurl","",2097,2112);
$z[2][4]=array();
$z[3]=Array("title","",2128,2142);
$z[3][4]=array();
$z[4]=Array("pubdate","",2191,2237);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2262,2276);
$z[5][4]=array();
$z[6]=Array("scores","",2301,2316);
$z[6][4]=array();
$z[7]=Array("description","",2349,2369);
$z[7][4]=array();

?>