<div class='itemCenter toubuhover' style="float: left; height: auto;		 width: 95px; margin-left: 5px;"><li><a hidefocus='true' style='outline:none; color: black ;' class='' href='{dede:field name='typeurl'/}'  onclick="return false;">{dede:field name='typename'/}<span class='itemName0'>
	

<div style="height: 40px; width: 95px; display: block; z-index: 2; position: absolute; left: 20px; top: 5px;">
{dede:channel type='son'}<li><a href="[field:typelink/]">[field:typename/]</a></li>{/dede:channel}
</div>


</span></a></li></div>