<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img  src='{@me['litpic']}'/></a>\"); ",581,770);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",2020,2037);
$z[1][4]=array();
$z[2]=Array("arcurl","",2052,2067);
$z[2][4]=array();
$z[3]=Array("title","",2083,2097);
$z[3][4]=array();
$z[4]=Array("pubdate","",2146,2192);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2217,2231);
$z[5][4]=array();
$z[6]=Array("scores","",2256,2271);
$z[6][4]=array();
$z[7]=Array("description","",2304,2324);
$z[7][4]=array();

?>