<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img  src='{@me['litpic']}'/></a>\"); ",612,801);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",1335,1350);
$z[1][4]=array();
$z[2]=Array("pubdate","",1425,1471);
$z[2][4]=array();
$z[2][4]['function']="GetDateTimeMK(@me)";
$z[3]=Array("arcurl","",1532,1547);
$z[3][4]=array();
$z[4]=Array("title","",1715,1729);
$z[4][4]=array();
$z[5]=Array("description","",1818,1881);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\"),200)";

?>