<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2' style=\"width:130px;height:67px;\"><img src='{@me['litpic']}'/></a>\"); ",581,802);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",2052,2069);
$z[1][4]=array();
$z[2]=Array("arcurl","",2084,2099);
$z[2][4]=array();
$z[3]=Array("title","",2115,2129);
$z[3][4]=array();
$z[4]=Array("pubdate","",2178,2224);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2249,2263);
$z[5][4]=array();
$z[6]=Array("scores","",2288,2303);
$z[6][4]=array();
$z[7]=Array("description","",2336,2356);
$z[7][4]=array();

?>