<?php
$z[0]=Array("typelink","",1870,1887);
$z[0][4]=array();
$z[1]=Array("arcurl","",1902,1917);
$z[1][4]=array();
$z[2]=Array("title","",1933,1947);
$z[2][4]=array();
$z[3]=Array("pubdate","",1996,2042);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",2067,2081);
$z[4][4]=array();
$z[5]=Array("scores","",2106,2121);
$z[5][4]=array();
$z[6]=Array("description","",2154,2174);
$z[6][4]=array();

?>