<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img  src='{@me['litpic']}'/></a>\"); ",589,778);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("pubdate","",1411,1457);
$z[1][4]=array();
$z[1][4]['function']="GetDateTimeMK(@me)";
$z[2]=Array("arcurl","",1490,1505);
$z[2][4]=array();
$z[3]=Array("title","",1693,1707);
$z[3][4]=array();
$z[4]=Array("description","",1799,1819);
$z[4][4]=array();

?>