<div class='itemCenter toubuhover' style="float: left; height: 40px;		 width: 95px; margin-left: 5px;"><li><a hidefocus='true' style='outline:none; ' class='topwen' href='{dede:field name='typeurl'/}'  onclick="return false;">{dede:field name='typename'/}<span class='itemName0'>
	


{dede:channel type='son'}<li class="xiala" style="background-color:#f13a3a ;"><a class="topwen" href="[field:typelink/]">[field:typename/]</a></li>{/dede:channel}



</span></a></li></div>