<li class='J_footerItemSection footerItemSection'>
																	<table class='J_footerItemContainer footerItemContainer'>
																		<tr>
																			<td class='footerItemContainer-firstTd' style='vertical-align:middle;'>
																				<div class='footerItemPic'>
																					<a href='javascript:void(0)' class='footerItemNormalPic ' style='text-decoration: none;' id='footerItemPic2'></a>
																				</div>
																			</td>
																			<td class='footerItemContainer-secondTd' style='vertical-align:middle;'>
																				<div class='footerItemContent'>
																					
																					<div class='footerItemTop'>
																						<a title='' class='footerItemTopLink' href='{dede:field name=' typeurl '/}' child='0'>{dede:field name='typename'/}<span class='fk-footerTriangle'></span></a>
																						<div class='fk-footerTrianglePlaceholder'></div>
																					</div>
																					
																					<div class='footerItemMiddle'>
																						<div class='footSplitline'></div>
																					</div>
																				</div>
																			</td>
																		</tr>
																	</table>
																</li>
																<li class='footerItemSpacing'>
																	<div class='footerVerticalLine'></div>
																</li>