<div topClassName='top1' topSwitch='on' newsId='287' newsName='智能风控将是大势所趋' class='J_newsListLine line J_nHover   newsListLine2  ' style='height:auto;'>
																									
																									<table id='lineBody287' class='J_lineBody lineBody' cellpadding='0' cellspacing='0'>
																										<tr id='module342tr287'>
																											<td class='J_newsTitle newsTitle mixNewsTitle' valign='top'>
																												<div class='J_articlePhotoBox articlePhotoBox ' newid='287' newsFlag='8'>
																													<a class='J_articlePicHref articlePicLink2' href='nd.jsp?id=287#_np=2_342' target='_blank' style='width:130px;height:67px;'><img class='J_newsListPic newsPic newsListNewPic'  alt="[field:title/]" src='[field:litpic/]' style='width:120px;height:67px;' /></a>
																												</div>
																												<div class='mixNewsStyleTitleContainer'>
																													<div class='J_newsListTopFlag  newsListTopFlag2'>
																														<a class='no-mixNewsStyleTitleTip' href='nd.jsp?id=287#_np=2_342' target='_blank'></a>
																													</div><span class='mixNewsStyleDate fk-newsListDate'>[field:pubdate function=MyDate('m-d',@me)/]</span>
																													<a hidefocus='true' href="nd.jsp?id=287#_np=2_342" target=_blank title='[field:textlink/]' class='J_mixNewsStyleTitle fk-newsListTitle mixNewsStyleTitle  pic-mixNewsStyleTitle ' mix='1'>[field:textlink/]</a>
																												</div>
																												<p class='mixNewsStyleSummary fk-newsListSummary  pic-mixNewsStyleSummary '>[field:description function='cn_substr(html2text(@me),100)'/][field:description function='cn_substr(html2text(@me),100)'/]</p>
																											</td>
																										</tr>
																									</table>
																									
<!--{dede:arclist row='3'typeid='11' titlelen='24' infolen='160'  orderby='pubdate' idlist='' col='2' imgwidth='120' imgheight='90'}
[field:textlink/]([field:pubdate function=MyDate('m-d',@me)/])<br/>
   <img src='[field:litpic/]'  alt="[field:title/]" /> 
   [field:description function='cn_substr(html2text(@me),100)'/]</p>-->