<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img class=\"J_newsListPic newsPic newsListNewPic\"  style=\"width:120px;height:67px;\" alt=\"文章附图\" title=\"\" src='{@me['litpic']}'/></a>\"); ",581,876);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",2126,2143);
$z[1][4]=array();
$z[2]=Array("arcurl","",2158,2173);
$z[2][4]=array();
$z[3]=Array("title","",2189,2203);
$z[3][4]=array();
$z[4]=Array("pubdate","",2252,2298);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2323,2337);
$z[5][4]=array();
$z[6]=Array("scores","",2362,2377);
$z[6][4]=array();
$z[7]=Array("description","",2410,2430);
$z[7][4]=array();

?>