<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a class=\"J_articlePicHref articlePicLink2\" href=\"nd.jsp?id=288#_np=104_380\" target=\"_blank\" style=\"width:130px;height:67px;\">\r\n				<img class=\"J_newsListPic newsPic newsListNewPic\" alt=\"文章附图\" title=\"\" src=\"//14436827.s21i.faiusr.com/2/ABUIABACGAAg1f7L5AUogJL9nwQwkAM4iwI!300x300.jpg\" style=\"width:120px;height:67px;\" data-bd-imgshare-binded=\"1\"></a>\"); ",582,1020);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",1867,2021);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[2]=Array("typelink","",2032,2049);
$z[2][4]=array();
$z[3]=Array("arcurl","",2064,2079);
$z[3][4]=array();
$z[4]=Array("title","",2095,2109);
$z[4][4]=array();
$z[5]=Array("pubdate","",2158,2204);
$z[5][4]=array();
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("click","",2229,2243);
$z[6][4]=array();
$z[7]=Array("scores","",2268,2283);
$z[7][4]=array();
$z[8]=Array("description","",2316,2336);
$z[8][4]=array();

?>