<div class="newsList J_newsList pic-mixNewsList " id="newsList380" _showsetting="1" newslisttype="2" scroll="0">
<div topclassname="top1" topswitch="on" newsid="288" newsname="P2P平台靠谱的十九妙计耀驰告诉你" class="J_newsListLine line J_nHover   newsListLine2  " style="height:auto;">
	<table id="lineBody288" class="J_lineBody lineBody" cellpadding="0" cellspacing="0"><tbody><tr id="module380tr288"><td class="J_newsTitle newsTitle mixNewsTitle" valign="top" style="width: 100%;">
		<div class="J_articlePhotoBox articlePhotoBox " newid="288" newsflag="0">
			 [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a class="J_articlePicHref articlePicLink2" href="nd.jsp?id=288#_np=104_380" target="_blank" style="width:130px;height:67px;">
				<img class="J_newsListPic newsPic newsListNewPic" alt="文章附图" title="" src="//14436827.s21i.faiusr.com/2/ABUIABACGAAg1f7L5AUogJL9nwQwkAM4iwI!300x300.jpg" style="width:120px;height:67px;" data-bd-imgshare-binded="1"></a>"); [/field:array]</div><div class="mixNewsStyleTitleContainer"><div class="J_newsListTopFlag  newsListTopFlag2"><a class="no-mixNewsStyleTitleTip" href="nd.jsp?id=288#_np=104_380" target="_blank"></a></div><span class="mixNewsStyleDate fk-newsListDate">2019-03-21</span><a hidefocus="true" href="nd.jsp?id=288#_np=104_380" target="_blank" title="P2P平台靠谱的十九妙计耀驰告诉你" class="J_mixNewsStyleTitle fk-newsListTitle mixNewsStyleTitle  pic-mixNewsStyleTitle" mix="1" style="width: 812px;">P2P平台靠谱的十九妙计耀驰告诉你</a></div><p class="mixNewsStyleSummary fk-newsListSummary  pic-mixNewsStyleSummary ">　　自P2P网贷上线以来，因为其高收益的优势，夺得了众多投资者的青睐。然而，水易载舟亦能覆舟，高收益的背后必然是高...</p>
</td>
</tr>

  <ul class="e2">
    
    <li> [field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>"); [/field:array]
     [<b>[field:typelink/]</b>] <a href="[field:arcurl/]" class="title">[field:title/]</a> <span class="info"> <small>日期：</small>[field:pubdate function="GetDateTimeMK(@me)"/] <small>点击：</small>[field:click/] <small>好评：</small>[field:scores/] </span>
     <p class="intro"> [field:description/]... </p>
    </li>
    
   
   </ul>
</tbody></table>