<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img  src='{@me['litpic']}'/></a>\"); ",581,770);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",780,797);
$z[1][4]=array();
$z[2]=Array("arcurl","",812,827);
$z[2][4]=array();
$z[3]=Array("title","",843,857);
$z[3][4]=array();
$z[4]=Array("pubdate","",906,952);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",977,991);
$z[5][4]=array();
$z[6]=Array("scores","",1016,1031);
$z[6][4]=array();
$z[7]=Array("description","",1064,1084);
$z[7][4]=array();

?>