<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",1768,1922);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",1933,1950);
$z[1][4]=array();
$z[2]=Array("arcurl","",1965,1980);
$z[2][4]=array();
$z[3]=Array("title","",1996,2010);
$z[3][4]=array();
$z[4]=Array("pubdate","",2059,2105);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2130,2144);
$z[5][4]=array();
$z[6]=Array("scores","",2169,2184);
$z[6][4]=array();
$z[7]=Array("description","",2217,2237);
$z[7][4]=array();

?>