<?php
$z[0]=Array("typelink","",1888,1905);
$z[0][4]=array();
$z[1]=Array("arcurl","",1920,1935);
$z[1][4]=array();
$z[2]=Array("title","",1951,1965);
$z[2][4]=array();
$z[3]=Array("pubdate","",2014,2060);
$z[3][4]=array();
$z[3][4]['function']="GetDateTimeMK(@me)";
$z[4]=Array("click","",2085,2099);
$z[4][4]=array();
$z[5]=Array("scores","",2124,2139);
$z[5][4]=array();
$z[6]=Array("description","",2172,2192);
$z[6][4]=array();

?>