<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2' target=\"_blank\" style=\"width:130px;height:67px;\"><img src='{@me['litpic']}'/></a>\"); ",581,818);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",2068,2085);
$z[1][4]=array();
$z[2]=Array("arcurl","",2100,2115);
$z[2][4]=array();
$z[3]=Array("title","",2131,2145);
$z[3][4]=array();
$z[4]=Array("pubdate","",2194,2240);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2265,2279);
$z[5][4]=array();
$z[6]=Array("scores","",2304,2319);
$z[6][4]=array();
$z[7]=Array("description","",2352,2372);
$z[7][4]=array();

?>