<?php
$z[0]=Array("litpic","",566,581);
$z[0][4]=array();
$z[1]=Array("textlink","",1748,1765);
$z[1][4]=array();
$z[2]=Array("pubdate","",1766,1809);
$z[2][4]=array();
$z[2][4]['function']="MyDate('m-d',@me)";
$z[3]=Array("litpic","",1830,1845);
$z[3][4]=array();
$z[4]=Array("title","",1853,1867);
$z[4][4]=array();
$z[5]=Array("description","",1877,1938);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(html2text(@me),100)";

?>