<?php
$z[0]=Array("textlink","",1318,1335);
$z[0][4]=array();
$z[1]=Array("textlink","",1792,1809);
$z[1][4]=array();
$z[2]=Array("pubdate","",1810,1853);
$z[2][4]=array();
$z[2][4]['function']="MyDate('m-d',@me)";
$z[3]=Array("litpic","",1874,1889);
$z[3][4]=array();
$z[4]=Array("title","",1897,1911);
$z[4][4]=array();
$z[5]=Array("description","",1921,1982);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(html2text(@me),100)";

?>