<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a class=\"J_articlePicHref articlePicLink2\" href=\"nd.jsp?id=288#_np=104_380\" target=\"_blank\" style=\"width:130px;height:67px;\">\r\n				<img class=\"J_newsListPic newsPic newsListNewPic\" alt=\"文章附图\" title=\"\" src=\"//14436827.s21i.faiusr.com/2/ABUIABACGAAg1f7L5AUogJL9nwQwkAM4iwI!300x300.jpg\" style=\"width:120px;height:67px;\" data-bd-imgshare-binded=\"1\"></a> ",582,1017);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",1966,1983);
$z[1][4]=array();
$z[2]=Array("arcurl","",1998,2013);
$z[2][4]=array();
$z[3]=Array("title","",2029,2043);
$z[3][4]=array();
$z[4]=Array("pubdate","",2092,2138);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2163,2177);
$z[5][4]=array();
$z[6]=Array("scores","",2202,2217);
$z[6][4]=array();
$z[7]=Array("description","",2250,2270);
$z[7][4]=array();

?>