<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",581,735);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",1603,1620);
$z[1][4]=array();
$z[2]=Array("arcurl","",1635,1650);
$z[2][4]=array();
$z[3]=Array("title","",1666,1680);
$z[3][4]=array();
$z[4]=Array("pubdate","",1729,1775);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",1800,1814);
$z[5][4]=array();
$z[6]=Array("scores","",1839,1854);
$z[6][4]=array();
$z[7]=Array("description","",1887,1907);
$z[7][4]=array();

?>