<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img class=\"J_newsListPic newsPic newsListNewPic\" alt=\"文章附图\" title=\"\" src='{@me['litpic']}'/></a>\"); ",581,842);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",2092,2109);
$z[1][4]=array();
$z[2]=Array("arcurl","",2124,2139);
$z[2][4]=array();
$z[3]=Array("title","",2155,2169);
$z[3][4]=array();
$z[4]=Array("pubdate","",2218,2264);
$z[4][4]=array();
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",2289,2303);
$z[5][4]=array();
$z[6]=Array("scores","",2328,2343);
$z[6][4]=array();
$z[7]=Array("description","",2376,2396);
$z[7][4]=array();

?>