<div class='itemCenter toubuhover' style="float: left; height: auto;		 width: 95px; margin-left: 5px;"><li><a hidefocus='true' style='outline:none; color: black ;' class='' href='{dede:field name='typeurl'/}'  onclick="return false;">{dede:field name='typename'/}<span class='itemName0'>
	


{dede:channel type='son'}<li style="position: absolute; top: 5px; width: 20px; height: 10px;"><a href="[field:typelink/]">[field:typename/]</a></li>{/dede:channel}



</span></a></li></div>