<table id='lineBody287' class='J_lineBody lineBody' cellpadding='0' cellspacing='0'>
																										<tr id='module342tr287'>
																											<td class='J_newsTitle newsTitle mixNewsTitle' valign='top'>
																												<div class='J_articlePhotoBox articlePhotoBox ' newid='287' newsFlag='8'>
																													<a class='J_articlePicHref articlePicLink2' href='nd.jsp?id=287#_np=2_342' target='_blank' style='width:130px;height:67px;'><img class='J_newsListPic newsPic newsListNewPic' alt='[field:title/]' title='' src='[field:litpic/]' style='width:120px;height:67px;' /></a>
																												</div>
																												<div class='mixNewsStyleTitleContainer'>
																													<div class='J_newsListTopFlag  newsListTopFlag2'>
																														<a class='no-mixNewsStyleTitleTip' href='nd.jsp?id=287#_np=2_342' target='_blank'></a>
																													</div><span class='mixNewsStyleDate fk-newsListDate'>2019-02-28</span>
																													<a hidefocus='true' href="[field:arcurl/]" target=_blank title="智能风控将是大势所趋" class='J_mixNewsStyleTitle fk-newsListTitle mixNewsStyleTitle  pic-mixNewsStyleTitle ' mix='1'>[field:title/]</a>
																												</div>
																												<p class='mixNewsStyleSummary fk-newsListSummary  pic-mixNewsStyleSummary '> [field:description function='cn_substr(html2text(@me),100)'/]</p>
																											</td>
																										</tr>
																									</table>