<?php
$z[0]=Array("field","",208,238);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",241,270);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel","<li class=\"xiala\" style=\"background-color:#f13a3a ; border-radius: 4px;\"><a class=\"\" style=\"color: #fff;\" href=\"[field:typelink/]\">[field:typename/]</a></li>",303,500);
$z[2][4]=array();
$z[2][4]['type']="son";

?>