<div topClassName='top1' topSwitch='on' newsId='287' newsName='智能风控将是大势所趋' class='J_newsListLine line J_nHover   newsListLine2  ' style='height:auto;'>
																									
																									<table id='lineBody287' class='J_lineBody lineBody' cellpadding='0' cellspacing='0'>
																										<tr id='module342tr287'>
																											<td class='J_newsTitle newsTitle mixNewsTitle' valign='top'>
																												<div class='J_articlePhotoBox articlePhotoBox ' newid='287' newsFlag='8'>
																													<a class='J_articlePicHref articlePicLink2' href='nd.jsp?id=287#_np=2_342' target='_blank' style='width:130px;height:67px;'><img class='J_newsListPic newsPic newsListNewPic' alt='文章附图' title='' src='//14436827.s21i.faiusr.com/2/ABUIABACGAAgtOnd4wUo6IbemQMwuAg44AQ!300x300.jpg' style='width:120px;height:67px;' /></a>
																												</div>
																												<div class='mixNewsStyleTitleContainer'>
																													<div class='J_newsListTopFlag  newsListTopFlag2'>
																														<a class='no-mixNewsStyleTitleTip' href='nd.jsp?id=287#_np=2_342' target='_blank'></a>
																													</div><span class='mixNewsStyleDate fk-newsListDate'>2019-02-28</span>
																													<a hidefocus='true' href="nd.jsp?id=287#_np=2_342" target=_blank title="智能风控将是大势所趋" class='J_mixNewsStyleTitle fk-newsListTitle mixNewsStyleTitle  pic-mixNewsStyleTitle ' mix='1'>智能风控将是大势所趋</a>
																												</div>
																												<p class='mixNewsStyleSummary fk-newsListSummary  pic-mixNewsStyleSummary '>金融行业已成为数字化程度最高的行业之一，其天然的“数字属性”以及历史沉淀下来的海量数据都为金融智能化转型提供了绝佳...</p>
																											</td>
																										</tr>
																									</table>
																									
<!--{dede:arclist row='3'typeid='11' titlelen='24' infolen='160'  orderby='pubdate' idlist='' col='2' imgwidth='120' imgheight='90'}
[field:textlink/]([field:pubdate function=MyDate('m-d',@me)/])<br/>
   <img src='[field:litpic/]'  alt="[field:title/]" /> 
   [field:description function='cn_substr(html2text(@me),100)'/]</p>-->