<?php
$z[0]=Array("title","",538,552);
$z[0][4]=array();
$z[1]=Array("litpic","",568,583);
$z[1][4]=array();
$z[2]=Array("pubdate","",1012,1054);
$z[2][4]=array();
$z[2][4]['function']="GetDateMK(@me)";
$z[3]=Array("arcurl","",1118,1133);
$z[3][4]=array();
$z[4]=Array("title","",1283,1297);
$z[4][4]=array();
$z[5]=Array("description","",1444,1505);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(html2text(@me),800)";

?>