<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a  href='{@me['arcurl']}' class='preview J_articlePicHref articlePicLink2'><img  src='{@me['litpic']}'/></a>\"); ",568,757);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",922,937);
$z[1][4]=array();
$z[2]=Array("pubdate","",1022,1068);
$z[2][4]=array();
$z[2][4]['function']="GetDateTimeMK(@me)";
$z[3]=Array("arcurl","",1134,1149);
$z[3][4]=array();
$z[4]=Array("title","",1272,1286);
$z[4][4]=array();
$z[5]=Array("description","",1385,1448);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\"),200)";

?>