<?php
$z[0]=Array("channelartlist","\r\n																<div class='itemCenter toubuhover' style=\"float: left; height: 40px;width: 95px; margin-left: 10px;\">\r\n																	<li>\r\n																		<a hidefocus='true' style='outline:none; ' class='topwen' href='{dede:field name=' typeurl '/}' >{dede:field name='typename'/}<span class='itemName0'>\r\n	\r\n\r\n\r\n{dede:channel type='son'}<li class=\"xiala\" style=\"background-color:#f13a3a ; border-radius: 4px;\"><a class=\"\" style=\"color: #fff;\" href=\"[field:typelink/]\">[field:typename/]</a></li>{/dede:channel}\r\n\r\n\r\n\r\n</span></a>\r\n																	</li>\r\n																</div>",1981,2622);
$z[0][4]=array();
$z[0][4]['typeid']="top";

?>