<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'6aaW6aG1');
$cfg_Cs[2]=array(0,1,1,'5ZCI5LyZ5Lq66K6h5YiS');
$cfg_Cs[3]=array(0,1,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[4]=array(0,1,1,'5paw6Ze75Yqo5oCB');
$cfg_Cs[5]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[6]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[7]=array(5,1,1,'5bqX6Z2i5bGV56S6');
$cfg_Cs[8]=array(3,1,1,'6L2m5oq16LS3');
$cfg_Cs[9]=array(3,1,1,'5Lul56ef5Luj6LSt');
$cfg_Cs[11]=array(4,1,1,'5pyA5paw5Yqo5oCB');
$cfg_Cs[12]=array(4,1,1,'5YWs5Y+45paw6Ze7');
$cfg_Cs[14]=array(4,1,1,'6KGM5Lia6LWE6K6v');
?>